config/routes.rb
Rails.application.routes.draw do
  resources :downloads
  resources :lessons
  resources :configs
  resources :years
  devise_for :users
  resources :posts
  resources :students
  resources :badges
  post 'students/:id/add_badge/:b_id' => 'students#add_badge' ,as: 'add_badge'
  root 'welcome#index'
  post 'students/import' => 'students#import', as: 'import_students'
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_one :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
	has_many :badger
	has_many :students , :through => :badger
	mount_uploader :image, StudentAvatarUploader
end

app/models/badger.rb
class Badger < ApplicationRecord
	belongs_to :badge
	belongs_to :student
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/download.rb
class Download < ApplicationRecord
	mount_uploader :file , DownloadFileUploader
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	mount_uploader :image, LessonImageUploader
	mount_uploader :file , LessonFileUploader
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, PostImageUploader
	mount_uploader :file , PostFileUploader
end

app/models/student.rb
class Student < ApplicationRecord
	mount_uploader :avatar, StudentAvatarUploader
	has_one :user
	has_one :year
	has_many :badges , :through => :badger
	has_many :badger
  # after_initialize :init

  def get_cred
  	self.fname + ' ' + self.lname
  end


  def self.import(file)
  	Spreadsheet.client_encoding = 'UTF-8'
  	tmp = file.tempfile
  	book = Spreadsheet.open tmp.path
  	sheet1 = book.worksheet 0
  	header = sheet1.row(0)
  	sheet1.each 1 do |row|
  		class_number = row[0]
  		class_name = row[1]
  		year = row[2]
  		first_name = row[3]
  		last_name = row[4]
  		username = row[5]
  		password = row[6]
  		student = Student.find_by(:username => username)
  		if student.nil?
  			student = Student.new
  			student.money = 0
  			student.points = 0
  			user = User.create!(:username=>username,:password=>password)
  		else
  			user = User.find_by(:username => username)
  		end
  		  	student.class_name = class_name
  			student.class_no = class_number
  			student.year_id = Year.find_by(:name => year).id
  			student.fname = first_name
  			student.lname = last_name
  			student.username = username
  			student.password = password
  			user.password = password
  			user.password_confirmation = password
  			student.user_id = user.id
  			user.save!
  			student.save!
  	end
  	FileUtils.rm tmp.path
  end



end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable,:rememberable, :trackable, :validatable

	def set_admin
		if (Admin.where(:user_id=>self.id).first ==nil)
			Admin.create!(:user_id=>self.id)
		end
	end

	def is_admin
		admin = Admin.where(:user_id=>self.id).first
		if admin == nil
			return false
		else 
			return true
		end
	end

	def get_student
		student = Student.where(:user_id=>self.id).first
		return student
	end
	def email_required?
		false
	end

	def email_changed?
		false
	end
end

app/models/year.rb
class Year < ApplicationRecord
	has_many :students
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  before_action :set_download, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:edit, :destroy, :new, :create]

  # GET /downloads
  # GET /downloads.json
  def index
    @downloads = Download.all
  end

  # GET /downloads/1
  # GET /downloads/1.json
  def show
  end

  # GET /downloads/new
  def new
    @download = Download.new
  end

  # GET /downloads/1/edit
  def edit
  end

  # POST /downloads
  # POST /downloads.json
  def create
    @download = Download.new(download_params)

    respond_to do |format|
      if @download.save
        format.html { redirect_to @download, notice: 'Download was successfully created.' }
        format.json { render :show, status: :created, location: @download }
      else
        format.html { render :new }
        format.json { render json: @download.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /downloads/1
  # PATCH/PUT /downloads/1.json
  def update
    respond_to do |format|
      if @download.update(download_params)
        format.html { redirect_to @download, notice: 'Download was successfully updated.' }
        format.json { render :show, status: :ok, location: @download }
      else
        format.html { render :edit }
        format.json { render json: @download.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /downloads/1
  # DELETE /downloads/1.json
  def destroy
    @download.destroy
    respond_to do |format|
      format.html { redirect_to downloads_url, notice: 'Download was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_download
      @download = Download.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def download_params
      params.require(:download).permit(:title, :desc, :file)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:edit, :destroy, :new, :create]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image,:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_year
		Config.first.current_year
	end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/downloads/_download_card.html.erb
<div class="post">
	<div class="post-body">
		<p class="clearfix">
			<span class="pull-right">
				<small class="mr-sm">
					<%= download.created_at.to_jalali.strftime("%A %d %B %Y") %>
				</small>
			</span>
		</p>
		<h4>
			<%= link_to download do %>
			<%= download.title %>
			<%end%>
		</h4>
		<p>
			<%= download.desc.gsub(/\n/, '<br/>').html_safe %>
		</p>
    <% if download.file?%>
          <%=  link_to 'دریافت فایل', download.file_url,:target=>'_blank',:class=>'btn btn-success',:id=>'post-file'%>
    <% end %>
	</div>
</div>
<br>
<% if user_signed_in? and current_user.is_admin %>
<span class="pull-left">
	<%= link_to 'Edit', edit_download_path(download) ,:class => 'btn btn-success  btn-xs' %> 
	<%= link_to 'Destroy', download,:class => 'btn btn-danger  btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %>
</span>
<% end %>


<br>
<br>

app/views/downloads/_form.html.erb
<%= form_for download,html: { multipart: true , :class =>'card' } do |f|  %>
  <% if download.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(download.errors.count, "error") %> prohibited this download from being saved:</h2>

      <ul>
      <% download.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title ,:class =>'form-control' %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc, id: :download_desc  ,:class => 'form-control'%>
  </div>
  
  <div class="field">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/downloads/edit.html.erb
<h1>Editing Download</h1>

<%= render 'form', download: @download %>

<%= link_to 'Show', @download %> |
<%= link_to 'Back', downloads_path %>

app/views/downloads/index.html.erb
<% @downloads.each do |download| %>
  <%= render 'download_card', :download => download %>
<% end %>

app/views/downloads/new.html.erb
<%= render 'form', download: @download %>

app/views/downloads/show.html.erb
<%= render 'download_card', :download => @download %>