config/routes.rb
Rails.application.routes.draw do
  resources :downloads
  resources :lessons
  resources :configs
  resources :years
  devise_for :users
  resources :posts
  resources :students
  resources :badges
  post 'students/:id/add_badge/:b_id' => 'students#add_badge' ,as: 'add_badge'
  root 'welcome#index'
  post 'students/import' => 'students#import', as: 'import_students'
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_one :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
	has_many :badger
	has_many :students , :through => :badger
	mount_uploader :image, StudentAvatarUploader
end

app/models/badger.rb
class Badger < ApplicationRecord
	belongs_to :badge
	belongs_to :student
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/download.rb
class Download < ApplicationRecord
	mount_uploader :file , DownloadFileUploader
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	mount_uploader :image, LessonImageUploader
	mount_uploader :file , LessonFileUploader
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, PostImageUploader
	mount_uploader :file , PostFileUploader
end

app/models/student.rb
class Student < ApplicationRecord
	mount_uploader :avatar, StudentAvatarUploader
	has_one :user
	has_one :year
	has_many :badges , :through => :badger
	has_many :badger
  # after_initialize :init

  def get_cred
  	self.fname + ' ' + self.lname
  end


  def self.import(file)
  	Spreadsheet.client_encoding = 'UTF-8'
  	tmp = file.tempfile
  	book = Spreadsheet.open tmp.path
  	sheet1 = book.worksheet 0
  	header = sheet1.row(0)
  	sheet1.each 1 do |row|
  		class_number = row[0]
  		class_name = row[1]
  		year = row[2]
  		first_name = row[3]
  		last_name = row[4]
  		username = row[5]
  		password = row[6]
  		student = Student.find_by(:username => username)
  		if student.nil?
  			student = Student.new
  			student.money = 0
  			student.points = 0
  			user = User.create!(:username=>username,:password=>password)
  		else
  			user = User.find_by(:username => username)
  		end
  		  	student.class_name = class_name
  			student.class_no = class_number
  			student.year_id = Year.find_by(:name => year).id
  			student.fname = first_name
  			student.lname = last_name
  			student.username = username
  			student.password = password
  			user.password = password
  			user.password_confirmation = password
  			student.user_id = user.id
  			user.save!
  			student.save!
  	end
  	FileUtils.rm tmp.path
  end



end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable,:rememberable, :trackable, :validatable

	def set_admin
		if (Admin.where(:user_id=>self.id).first ==nil)
			Admin.create!(:user_id=>self.id)
		end
	end

	def is_admin
		admin = Admin.where(:user_id=>self.id).first
		if admin == nil
			return false
		else 
			return true
		end
	end

	def get_student
		student = Student.where(:user_id=>self.id).first
		return student
	end
	def email_required?
		false
	end

	def email_changed?
		false
	end
end

app/models/year.rb
class Year < ApplicationRecord
	has_many :students
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:edit,:update,:destroy,:create,:new]
  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
    if user_signed_in? and !current_user.is_admin
      @studentBadges = current_user.get_student.badges
    end
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_badge
    @badge = Badge.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def badge_params
    params.require(:badge).permit(:name, :price, :description, :image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:edit, :destroy, :new, :create]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image,:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_year
		Config.first.current_year
	end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/badges/_badge_card.html.erb
<div class="badge-card">
  <div class="row">
    <div class="col-md-8 col-xs-8 col-lg-8 col-sm-8">
      <div class="badge-info">
        <label>نشان</label>
        <%= badge.name %>
        <br>
        <label>امتیاز :</label>
        <span class='badge badge-warning'><%= badge.price %></span>
        <br>
        <%= badge.description %>
        <br>
        <br>
        <% if user_signed_in? and !current_user.is_admin %>
            <% unless studentBadges.include?(badge) %>
                <%= link_to add_badge_path(:id => current_user.get_student.id, :b_id => badge.id),
                            :method =>'POST' ,:class => 'btn btn-success' do %>
                    <i class="fa fa-money" aria-hidden="true"></i>
                    خرید
                <% end %>
            <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4 col-xs-4 col-lg-4 col-sm-4">
      <div class="badge-pic">
        <%= link_to badge  do %>
            <%= image_tag badge.image %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>
<% if user_signed_in? and current_user.is_admin %>
    <span class="pull-left">
	<%= link_to 'Edit', edit_badge_path(badge) ,:class => 'btn btn-success  btn-xs' %>
      <%= link_to 'Destroy', badge,:class => 'btn btn-danger  btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %>
</span>
<% end %>

app/views/badges/_form.html.erb
<%= form_for(badge) do |f| %>
  <% if badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% badge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<% @badges.each do |badge| %>
    <%= render 'badge_card', :badge => badge ,:studentBadges =>@studentBadges%>
<% end %>

app/views/badges/new.html.erb
<%= render 'form', badge: @badge %>

app/views/badges/show.html.erb
<%= render 'badge_card', :badge => @badge %>