config/routes.rb
Rails.application.routes.draw do
  resources :downloads
  resources :lessons
  resources :configs
  resources :years
  devise_for :users
  resources :posts
  resources :students
  resources :badges
  post 'students/:id/add_badge/:b_id' => 'students#add_badge' ,as: 'add_badge'
  root 'welcome#index'
  post 'students/import' => 'students#import', as: 'import_students'
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_one :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
	has_many :badger
	has_many :students , :through => :badger
	mount_uploader :image, StudentAvatarUploader
end

app/models/badger.rb
class Badger < ApplicationRecord
	belongs_to :badge
	belongs_to :student
end

app/models/config.rb
class Config < ApplicationRecord
end

app/models/download.rb
class Download < ApplicationRecord
	mount_uploader :file , DownloadFileUploader
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	mount_uploader :image, LessonImageUploader
	mount_uploader :file , LessonFileUploader
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, PostImageUploader
	mount_uploader :file , PostFileUploader
end

app/models/student.rb
class Student < ApplicationRecord
	mount_uploader :avatar, StudentAvatarUploader
	has_one :user
	has_one :year
	has_many :badges , :through => :badger
	has_many :badger
  # after_initialize :init

  def get_cred
  	self.fname + ' ' + self.lname
  end


  def self.import(file)
  	Spreadsheet.client_encoding = 'UTF-8'
  	tmp = file.tempfile
  	book = Spreadsheet.open tmp.path
  	sheet1 = book.worksheet 0
  	header = sheet1.row(0)
  	sheet1.each 1 do |row|
  		class_number = row[0]
  		class_name = row[1]
  		year = row[2]
  		first_name = row[3]
  		last_name = row[4]
  		username = row[5]
  		password = row[6]
  		student = Student.find_by(:username => username)
  		if student.nil?
  			student = Student.new
  			student.money = 0
  			student.points = 0
  			user = User.create!(:username=>username,:password=>password)
  		else
  			user = User.find_by(:username => username)
  		end
  		  	student.class_name = class_name
  			student.class_no = class_number
  			student.year_id = Year.find_by(:name => year).id
  			student.fname = first_name
  			student.lname = last_name
  			student.username = username
  			student.password = password
  			user.password = password
  			user.password_confirmation = password
  			student.user_id = user.id
  			user.save!
  			student.save!
  	end
  	FileUtils.rm tmp.path
  end



end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable,:rememberable, :trackable, :validatable

	def set_admin
		if (Admin.where(:user_id=>self.id).first ==nil)
			Admin.create!(:user_id=>self.id)
		end
	end

	def is_admin
		admin = Admin.where(:user_id=>self.id).first
		if admin == nil
			return false
		else 
			return true
		end
	end

	def get_student
		student = Student.where(:user_id=>self.id).first
		return student
	end
	def email_required?
		false
	end

	def email_changed?
		false
	end
end

app/models/year.rb
class Year < ApplicationRecord
	has_many :students
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Minecraft</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application'%>
	<%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
	<div class="container-fluid">
		<div class="col-xs-8 col-sm-8 col-md-offset-2 col-md-6 col-lg-offset-2 col-lg-6">
			<%= yield %>
			<br>
		</div>
		<div class="col-md-offset-2 col-lg-offset-2 col-md-2 col-xs-4 col-lg-2 col-sm-4">
			<div class="sidebar">
				<% if user_signed_in? and !current_user.is_admin %>
				<div>
					<%= link_to current_user.get_student ,:class=>'btn btn-success' do%>
					<i class="fa fa-user-circle" aria-hidden="true"></i>
					صفحه شخصی من
					<% end %>
				</div>
				<% end %>
				<div>
					<%= link_to root_path do %>
					<i class="fa fa-home" aria-hidden="true"></i>
					خانه
					<% end %>
				</div>
				<div>
					<%= link_to lessons_path do %>
					<i class="fa fa-book" aria-hidden="true"></i>
					دروس
					<% end %>
				</div>
				<div>
					<%= link_to downloads_path do %>
					<i class="fa fa-download" aria-hidden="true"></i>
					دانلود ها
					<% end %>
				</div>
				<div>
					<%= link_to students_path do %>
					<i class="fa fa-users" aria-hidden="true"></i>
					دانش آموزان
					<% end %>
				</div>
<!-- 				<div>
					<%= link_to badges_path do %>
					<i class="fa fa-certificate" aria-hidden="true"></i>
					نشان ها
					<% end %>
				</div> -->
				<% if user_signed_in? %>
				<% if current_user.is_admin %>
				<div>
					<%= link_to new_post_path do %>
					<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
					پست جدید
					<% end %>
				</div>

				<div>
					<%= link_to new_download_path do %>
					<i class="fa fa-download" aria-hidden="true"></i>
					دانلود جدید
					<% end %>
				</div>

				<div>
					<%= link_to new_lesson_path do %>
					<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
					درس جدید
					<% end %>
				</div>
				<div>
					<%= link_to new_student_path do %>
					<i class="fa fa-address-card" aria-hidden="true"></i>
					دانش آموز جدید
					<% end %>
				</div>
				<div>
					<%= link_to new_badge_path do %>
					<i class="fa fa-life-ring" aria-hidden="true"></i>
					نشان جدید
					<% end %>
				</div>
				<div>
					<%= link_to years_path do %>
					<i class="fa fa-cog" aria-hidden="true"></i>
سال های تحصیلی
					<% end %>
				</div>
				<div>
					<%= link_to configs_path do %>
					<i class="fa fa-cog" aria-hidden="true"></i>
					تنظیمات
					<% end %>
				</div>
				<% end %>
				<div>
					<%= link_to destroy_user_session_path ,:method => 'delete' do %>
					<i class="fa fa-sign-out" aria-hidden="true"></i>
					خروج
					<% end %>
				</div>
				<% else %>
				<div>
					<%= link_to new_user_session_path  do %>
					<i class="fa fa-sign-in" aria-hidden="true"></i>
					ورود
					<% end %>
				</div>
				<%end%>

			</div>
		</div>
	</div>
</body>
</html>